# Generated by Django 4.0.6 on 2022-10-08 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kana', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Book',
                'ordering': ['name', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kana', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('post_no', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^[0-9]{7}$', '7桁の数字を入力してください。')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='relationships.book')),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['name', 'age', 'book'],
            },
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kana', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{10,11}$', '10か11桁の数字を入力してください。')])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationships.customer')),
            ],
            options={
                'db_table': 'Workplace',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('holder', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{7}$', '7桁の数字を入力してください。')])),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Ordinary'), (1, 'Current')], default=0)),
                ('bank', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='relationships.customer')),
            ],
            options={
                'db_table': 'Bank',
            },
        ),
    ]
