name: Tests
on: [push]
jobs:
  test:
    name: Run Test Code
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: look inside .env.local before decrypting
      #   run: cat .env.local
      # - name: look at files inside repository
      #   run: ls -la
      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
      #   env:
      #     GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      # - name: look inside .env.local after decrypting
      #   run: cat .env.local
      # - name: look at files inside repository
      #   run: ls -la
      # - name: look at permissions of .git/git-crypt/keys/default
      #   run: ls -la .git/git-crypt/keys/default
      # - name: investigate the user
      #   run: whoami
      - name: give permissions to execute .git/git-crypt/keys/default
        run: sudo chmod 755 .git/git-crypt/keys/default
      - name: Test
        run:
          docker-compose run --rm app sh -c "poetry run python manage.py test"
